import numpy as np
import tensorflow as tf
from tensorflow import keras
from Bio import SeqIO
from Bio.Seq import Seq
from collections import Counter
import os
import sys
import argparse
import csv

# sys.path.append(
#     os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..')))

from utils import get_label_data, SUPERF_DICT, NUM_CLASSES, DNA_BASES
from models import make_generator_model

NOISE_DIM = 100
SEQ_LEN = 600
CHANNELS = 4
LIMITS_CSV = 'optimal_synthetic_limits.csv'

TES = {
    "retrotransposones": [
        "GYPSY", "CR1", "ERV", "COPIA", "L1", "RTE", "BELPAO", "I", "LINE",
        "DIRS", "LTR", "PLE", "SINE", "ALU", "R1"
    ],
    "transposones": [
        "TC1MARINER", "HAT", "TIR", "HELITRON", "PIFHARBINGER", "MULE",
        "CACTA", "LARD", "PIGGYBAC", "KOLOBOK", "ACADEM-1", "P", "MERLIN",
        "CRYPTON", "TRNA"
    ]
}

SUPERF_TO_ORDER = {
    # Retrotransposones
    'GYPSY': 'LTR',
    'COPIA': 'LTR',
    'ERV': 'LTR',
    'BELPAO': 'LTR',
    'LTR': 'LTR',
    'L1': 'LINE',
    'RTE': 'LINE',
    'I': 'LINE',
    'LINE': 'LINE',
    'CR1': 'LINE',
    'R1': 'LINE',
    'DIRS': 'DIRS',
    'LARD': 'DIRS',
    'PLE': 'PLE',
    'SINE': 'SINE',
    'ALU': 'SINE',
    'TRNA': 'SINE',

    # Transposones
    'TC1MARINER': 'TIR',
    'HAT': 'TIR',
    'TIR': 'TIR',
    'PIFHARBINGER': 'TIR',
    'MULE': 'TIR',
    'CACTA': 'TIR',
    'PIGGYBAC': 'TIR',
    'KOLOBOK': 'TIR',
    'ACADEM-1': 'TIR',
    'P': 'TIR',
    'MERLIN': 'TIR',
    'HELITRON': 'HELITRON',
    'CRYPTON': 'CRYPTON'
}

def decode_one_hot_to_sequence(one_hot_sequence):
    """
    Decodifica una secuencia one-hot a una secuencia de DNA
    """
    indices = np.argmax(one_hot_sequence, axis=-1)
    base_map = {i: base for i, base in enumerate(DNA_BASES)}
    sequence = "".join([base_map.get(idx, 'N') for idx in indices])
    return sequence.replace('N', '')


def generate_synthetic_sequences(generator, target_class_idx,
                                 num_samples_to_generate):
    """
    Genera secuencias sinteticas condicionadas a una clase.
    """
    print(
        f"  -> Generando {num_samples_to_generate} muestras para la clase {target_class_idx}..."
    )
    noise = tf.random.normal(shape=(num_samples_to_generate, NOISE_DIM))
    target_labels = tf.one_hot([target_class_idx] * num_samples_to_generate,
                               depth=NUM_CLASSES)
    synthetic_oh = generator([noise, target_labels], training=False).numpy()

    synthetic_sequences = []
    inv_superf_dict = {v: k for k, v in SUPERF_DICT.items()}
    class_name = inv_superf_dict[target_class_idx]

    for i, oh_seq in enumerate(synthetic_oh):
        seq = decode_one_hot_to_sequence(oh_seq)
        record = SeqIO.SeqRecord(
            Seq(seq),
            id=f"Synthetic_TE_{class_name}_{i:05d}",
            description=f"Generated by cGAN for class: {class_name}",
        )
        record.seq = record.seq.lower()

        order_name = SUPERF_TO_ORDER.get(class_name.upper(), "UNKNOWN")
        record.id = f"{record.id}#{order_name}/{class_name}"
        synthetic_sequences.append(record)
    return synthetic_sequences


def jensen_shannon_divergence(P, Q):
    """
    Calcula la distancia de JSD entre dos distribuciones
    """
    P = P / np.sum(P)
    Q = Q / np.sum(Q)
    M = 0.5 * (P + Q)

    P_non_zero = P[P > 0]
    M_for_P = M[P > 0]
    dkl_p = np.sum(P_non_zero * np.log2(P_non_zero / M_for_P))

    Q_non_zero = Q[Q > 0]
    M_for_Q = M[Q > 0]
    dkl_q = np.sum(Q_non_zero * np.log2(Q_non_zero / M_for_Q))

    return (0.5 * dkl_p + 0.5 * dkl_q)


def get_real_sequences_for_class(fasta_path, target_class_idx):
    """
    Extrae secuencias reales para una clase específica
    """
    real_sequences = []
    for record in SeqIO.parse(fasta_path, "fasta"):
        if get_label_data(record.id) == target_class_idx:
            real_sequences.append(str(record.seq).upper())
    return real_sequences


def extract_species_id(record_id, species_regex):
    """
    Extrae el ID de especie mediante regex
    """
    try:
        if species_regex:
            m = re.search(species_regex, record_id)
            if m:
                return m.group(1)
    except Exception:
        pass
    return 'GLOBAL'


def get_species_data(fasta_path, species_regex):
    """
    Construye mapas de especie a secuencias reales y a conteos por clase
    """
    species_to_sequences = {}
    species_to_class_counts = {}
    for record in SeqIO.parse(fasta_path, "fasta"):
        species_id = extract_species_id(record.id, species_regex)
        class_idx = get_label_data(record.id)
        if class_idx == -1:
            continue
        species_to_sequences.setdefault(species_id,
                                        []).append(str(record.seq).upper())
        species_to_class_counts.setdefault(species_id, Counter())
        species_to_class_counts[species_id][class_idx] += 1
    return species_to_sequences, species_to_class_counts


def kneedle_knee_point(x_vals, y_vals):
    """
    Detecta el punto de codo por distancia máxima a la línea entre extremos
    """
    if len(x_vals) < 3:
        return len(x_vals) - 1
    x0, y0 = x_vals[0], y_vals[0]
    xN, yN = x_vals[-1], y_vals[-1]
    dx = xN - x0
    dy = yN - y0
    denom = (dx**2 + dy**2)**0.5 or 1.0
    max_dist = -1.0
    knee_idx = len(x_vals) - 1
    for i in range(1, len(x_vals) - 1):
        xi, yi = x_vals[i], y_vals[i]
        num = abs(dy * (xi - x0) - dx * (yi - y0))
        dist = num / denom
        if dist > max_dist:
            max_dist = dist
            knee_idx = i
    return knee_idx


def plot_pca(real_sequences, synth_sequences, title, output_file):
    """
    grafico PCA comparando secuencias reales y sintéticas
    """
    real_profiles = np.array([sequence_to_kmer_profile([s], k=KMER_SIZE) for s in real_sequences])
    synth_profiles = np.array([sequence_to_kmer_profile([s], k=KMER_SIZE) for s in synth_sequences])
    
    X = np.concatenate([real_profiles, synth_profiles], axis=0)
    
    pca = PCA(n_components=2)
    X_pca = pca.fit_transform(X)
    
    real_pca = X_pca[:len(real_profiles)]
    synth_pca = X_pca[len(real_profiles):]
    
    plt.figure(figsize=(10, 8))
    plt.scatter(real_pca[:, 0], real_pca[:, 1], alpha=0.5, label='Real', c='blue', s=15)
    plt.scatter(synth_pca[:, 0], synth_pca[:, 1], alpha=0.5, label='Sintético', c='orange', s=15)
    
    plt.title(f'PCA Analysis - {title}')
    plt.xlabel('PC1')
    plt.ylabel('PC2')
    plt.legend()
    plt.grid(True, alpha=0.3)
    
    plt.savefig(output_file, dpi=300)
    plt.close()
    print(f"PCA guardado en: {output_file}")

